from django.urls import path
from .views import (
    BudgetLoginView,
    BudgetLogoutView,
    add_expense,
    admin_stats,
    ai_insights,
    budgets,
    charts,
    categories,
    delete_budget,
    delete_expense,
    delete_category,
    delete_goal,
    download_chart_csv,
    download_chart_svg,
    dashboard,
    edit_budget,
    edit_category,
    edit_expense,
    edit_goal,
    expense_list,
    goals,
    register,
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('register/', register, name='register'),
    path('login/', BudgetLoginView.as_view(), name='login'),
    path('logout/', BudgetLogoutView.as_view(), name='logout'),
    path('expenses/', expense_list, name='expense_list'),
    path('expenses/add/', add_expense, name='add_expense'),
    path('expenses/<int:expense_id>/edit/', edit_expense, name='edit_expense'),
    path('expenses/<int:expense_id>/delete/', delete_expense, name='delete_expense'),
    path('categories/', categories, name='categories'),
    path('categories/<int:category_id>/edit/', edit_category, name='edit_category'),
    path('categories/<int:category_id>/delete/', delete_category, name='delete_category'),
    path('budgets/', budgets, name='budgets'),
    path('budgets/<int:budget_id>/edit/', edit_budget, name='edit_budget'),
    path('budgets/<int:budget_id>/delete/', delete_budget, name='delete_budget'),
    path('goals/', goals, name='goals'),
    path('goals/<int:goal_id>/edit/', edit_goal, name='edit_goal'),
    path('goals/<int:goal_id>/delete/', delete_goal, name='delete_goal'),
    path('charts/', charts, name='charts'),
    path('charts/<str:chart_key>/download-svg/', download_chart_svg, name='download_chart_svg'),
    path('charts/<str:chart_key>/download-csv/', download_chart_csv, name='download_chart_csv'),
    path('insights/', ai_insights, name='ai_insights'),
    path('admin-stats/', admin_stats, name='admin_stats'),
]
